name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - xeus-lua
  - xeus-nelson
  - xeus-sql
  - xeus-cpp
  - numpy
  - matplotlib
  - pillow
  - ipywidgets
  - pip:
      - ipycanvas
      - jupyterlite-p5-kernel
  # Core modules (mandatory)
  - jupyterlite-core
  - jupyterlab
  - notebook
  # JavaScript kernel (optional)
  - jupyterlite-javascript-kernel
  # Language support (optional)
  - jupyterlab-language-pack-fr-FR
# P5 kernel (optional)
#jupyterlite-p5-kernel==0.1.0
# JupyterLab: Fasta file renderer (optional)
  - jupyterlab-fasta>=3.3.0,<4
# JupyterLab: Geojson file renderer (optional)
  - jupyterlab-geojson>=3.4.0,<4
# JupyterLab: guided tour (optional)
# TODO: re-enable after https://github.com/jupyterlab-contrib/jupyterlab-tour/issues/82
# jupyterlab-tour
# JupyterLab: dark theme
  - jupyterlab-night
# JupyterLab: Miami nights theme (optional)
  - jupyterlab_miami_nights
  
  # Python: ipyevents library for Jupyter notebooks (optional)
  - ipyevents
  # Python: interative Matplotlib library for Jupyter notebooks (optional)
  - ipympl
  # Python: ipyleaflet library for Jupyter notebooks (optional)
  - ipyleaflet
  # Python: plotting libraries (optional)
  - plotly
  - bqplot
